### ISSUE TITLE
Failed to run example: gl is null

### ISSUE THREAD

**Issue by Traveller23** [zhobo63/imgui-ts#6]
I created a simple webpack project and added the sample code to it. It compiled successfully, but when executing, the page went blank and I found the following error message in my browser's console:

```
Uncaught TypeError: Cannot read properties of null (reading 'COLOR_BUFFER_BIT')
    at Module.ClearBuffer (imgui_impl.ts:466:71)
    at _loop (index.ts:17:5)
```

Here is the entire contents of index.ts:
```typescript
import {ImGui, ImGui_Impl} from '@zhobo63/imgui-ts'

let text: ImGui.ImStringBuffer = new ImGui.ImStringBuffer(128, 'input text');
let text_area: ImGui.ImStringBuffer = new ImGui.ImStringBuffer(128, 'edit multiline');

function _loop(time: number): void {
    ImGui_Impl.NewFrame(time);
    ImGui.NewFrame();
    ImGui.Begin("Hello");
    ImGui.Text("Version " + ImGui.VERSION);
    ImGui.InputText("Input", text);
    ImGui.InputTextMultiline("Text", text_area);
    ImGui.End();
    ImGui.EndFrame();
    ImGui.Render();

    ImGui_Impl.ClearBuffer(new ImGui.ImVec4(0.25, 0.25, 0.25, 1));
    ImGui_Impl.RenderDrawData(ImGui.GetDrawData());
    window.requestAnimationFrame(_loop);
}

window.addEventListener('DOMContentLoaded', async () => {
    await ImGui.default();

    ImGui.CHECKVERSION();
    ImGui.CreateContext();
    const io: ImGui.IO = ImGui.GetIO();
    ImGui.StyleColorsDark();
    io.Fonts.AddFontDefault();

    const canvas: HTMLCanvasElement = document.getElementById("canvas") as HTMLCanvasElement;
    ImGui_Impl.Init(canvas);
    window.requestAnimationFrame(_loop);
});
```

@zhobo63/imgui-ts version: 0.1.41
This is my project: [demo.zip](https://github.com/zhobo63/imgui-ts/files/12572329/demo.zip)

How to reproduce:
```bash
# Download and unzip the demo project
npm install
npx webpack
# Open dist/index.html in your browser
```

**Comment by zhobo63** [comment]
your index.html doesn't contain <canvas id="canvas"></canvas>

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Demo</title>
</head>
<body>
    <canvas id="canvas"></canvas>
    <script src="bundle.js"></script>
</body>
</html>
```

**Comment by Traveller23** [comment]
Thanks, I realized that was the reason too, but I forgot to reply.
